model_name: "here_kitty_kitty"

target_phrases:
  - "here kitty kitty"
  - "heyo kitty cat"

negative_phrases:
  - "she pretty pretty"
  - "may know this or that"

training_samples: 25000
testing_samples: 5000

layer_size: 64

steps: 50000
target_fp: 0.2